var livro = new Object()
livro.titulo = 'Ajax com JQuery'
livro.autor = 'Maurìcio Smy Silva'
livro.paginas = 432
livro.preco = 'R$69,00'
livro.frete = 'Fazer cálculo (função)'
livro.capitulo1 = 'Revisão do Ajax'
livro.capitulo2 = 'Funções para requisições Ajax'
livro.capitulo3 = 'Eventos e Miscelânia'
livro.capitulo4 = 'Requisições XML'
livro.capitulo5 = 'Introdução ao formato JSON'
livro.capitulo6 = 'Requisições JSON'